config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Line Counter Routes
#get 'counter_repositories', :to => 'counter_repositories#index'
#get 'counter_repositories/new/:project_id', :to => 'counter_repositories#new', :as => 'new_line_counter_repository'
#post 'counter_repositories/new/:project_id', :to => 'counter_repositories#create', :as => 'create_line_counter_repository'
#get 'counter_repositories/:repository_id/edit', :to => 'counter_repositories#edit', :as => 'edit_line_counter_repository'
#delete 'counter_repositories/:repository_id', :to => 'counter_repositories#destroy'
#put 'counter_repositories', :to => 'counter_repositories#update'

resources :counter_repositories
resources :monitoring

# Branches Routes
get 'branches/new', :to => 'branches#new'
get 'projects/:id/monitoring', :to => 'monitoring#index'
post 'project/settings/monitoring', :to => 'projects#monitoring_settings'
post 'branches/append', :to => 'branches#append'
post 'branches', :to => 'branches#create'
delete 'branches/:issue_id', :to => 'branches#destroy'

app/models/branch.rb
require 'rugged'

class Branch < ActiveRecord::Base

  unloadable

  attr_accessible :name, :counter_repository, :issue, :diff

  belongs_to :issue
  belongs_to :counter_repository

  def get_diff
    count = 0
    repo = Rugged::Repository.new(counter_repository.url)
    diff = repo.diff(name, 'master')

    diff.each_patch do |patch|
      patch.hunks.each do |hunk|
        hunk.lines.each do |line|
          count = count + 1 if (line.new_lineno == -1 && !line.content.blank?)          
        end
      end
    end
    count
  end
end

app/models/correction_factor.rb
class CorrectionFactor < ActiveRecord::Base
  unloadable
  attr_accessible :complexity, :project, :tracker, :value

  belongs_to :project
  belongs_to :tracker

  validates :complexity, inclusion: { in: %w(Low Medium High) }
end

app/models/counter_repository.rb
require 'rugged'
class CounterRepository < ActiveRecord::Base
  unloadable

  attr_accessible :name, :url, :project

  belongs_to :project

  def branches
    repo = Rugged::Repository.new(url)
    repo.branches
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  def new
    @issue = Issue.find(params[:issue])
    @repositories = CounterRepository.where(:project_id => @issue.project_id).all
  end

  def append
    @issue = Issue.find(params[:issue])
    @branches = []

    params[:branch][:branch_ids].each do |val|
      branch_name = val.split(',')[1]
      if Branch.where(:issue_id => @issue.id, :name => branch_name).first.nil?
        repository_id = val.split(',')[0]
        repository = CounterRepository.find(repository_id)
        branch = Branch.new
        branch.name = branch_name
        branch.counter_repository = repository
        branch.issue = @issue
        branch.save!
        @branches << branch
      end
    end

  end

  def destroy
    @issue = Issue.find(params[:issue_id])
    branch = Branch.find(params[:branch_id])
    branch.destroy
  end

end

app/controllers/counter_repositories_controller.rb
class CounterRepositoriesController < ApplicationController
  unloadable

  def index
    @project = Project.find(params[:id])
    @repositories = CounterRepository.where(:project_id => @project.id).all
  end

  def new
    @project = Project.find(params[:format])
    @repository = CounterRepository.new(:project => @project)
  end

  def create
    @project = Project.find(params[:project_id])
    @repository = CounterRepository.new(params[:counter_repository])
    @repository.project_id = @project.id
    if @repository.valid?
      @repository.save!
      flash[:notice] = l(:notice_successful_create)
    end
    @repositories = CounterRepository.where(:project_id => @project.id).all
    redirect_to action: 'index', id: @project.identifier
  end

  def edit
    @repository = CounterRepository.find(params[:id])
    @project = Project.find(@repository.project_id)
  end

  def update
    @repository = CounterRepository.find(params[:id])
    @repository.update_attributes(params[:counter_repository])
    @project = Project.find(@repository.project_id)
    if !@repository.save!
      flash[:error] = t(:error)
      render :edit
    else
      flash[:notice] = t(:notice_successful_update)
      redirect_to action: 'index', id: @project.identifier
    end
  end

  def destroy
    repo = CounterRepository.find(params[:id])
    @project = Project.find(repo.project_id)
    @repositories = CounterRepository.where(:project_id => @project.id).all

    if repo.destroy
      flash[:notice] = l(:notice_successful_delete)
    end
    redirect_to action: 'index', id: @project.identifier
  end

end

app/helpers/branches_helper.rb
module BranchesHelper
  # Returns a comma separated list of users watching the given issue
  def branches_list(branches)
    #remove_allowed = User.current.allowed_to?("delete_#{issue.class.name.underscore}_watchers".to_sym, issue.project)
    content = ''.html_safe
    branches.each do |branch|
      s = ''.html_safe
      #if remove_allowed
      url = {:controller => 'branches',
             :action => 'destroy',
             :issue_id => branch.issue,
             :branch_id => branch}
      s << "#{branch.name} ".html_safe
      s << link_to(image_tag('delete.png'), url,
                   :remote => true, :method => 'delete', :class => "delete")
      #end
      content << content_tag('li', s, :class => "branch-#{branch.id}", :id =>"issue_branch_id_#{branch.id}")
    end
    content.present? ? content_tag('ul', content, :class => 'branches') : content
  end

end

app/views/branches/_branches.html.erb
<% if @issue %>
    <div id="branches">
      <div class="contextual">
        <%= link_to l(:button_add),
                    {:controller => 'branches', :action => 'new', :issue => @issue},
                    :remote => true,
                    :method => 'get' %>
      </div>

      <h3><%= l(:label_issue_branches) %> (<%= @issue.branches.size %>)</h3>
      <%= branches_list(@issue.branches.all) %>

    </div>

<% end %>

app/views/branches/_diff.html.erb
<hr>
<p><strong>Branches</strong></p>
<ul>
  <% @issue.branches.each do |branch| %>
      <p>
      <li>
        <strong> <%= branch.counter_repository.name %></strong> - <%= branch.name %>
        | <%= branch.diff %> <%= l(:lines) %>
      </li>
      </p>
  <% end %>
</ul>

app/views/branches/_form.html.erb
<p id="branches_form"><label><%= l(:label_issue_branches) %></label>
      <span id="branches_inputs">
        <%= branches_checkboxes(@issue) %>
      </span>

</p>

app/views/branches/_new.html.erb
<h3 class="title"><%= l(:add_issue_branches) %></h3>

<%= form_tag({:controller => 'branches',
              :action => ('append'),
              :issue => @issue,
              :project_id => @issue.project.id},
             :remote => true,
             :method => :post,
             :id => 'new-branch-form') do %>

    <div id="branches_for_issue">
      <% @repositories.each do |rep| %>
          <p><strong><%= "#{rep.name}" %></strong></p>
          <% rep.branches.each do |branch| %>
              <p><%= check_box_tag 'branch[branch_ids][]', "#{rep.id},#{branch.name}" %> <%= branch.name %></p>
          <% end %>
      <% end %>
    </div>
    <p class="buttons">
      <%= submit_tag l(:button_add), :name => nil, :onclick => "hideModal(this);" %>
      <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
    </p>
<% end %>

app/views/branches/append.js.erb
<% @branches.each do |branch| %>
$("#issue_branch_id_<%= branch.id %>").remove();
<% end %>
$('#branches_inputs').append('<%= escape_javascript(branches_list(@branches)) %>');
location.reload();

app/views/branches/destroy.js.erb
$('#branches').html('<%= escape_javascript(render(:partial => 'branches/branches', :locals => {:issue => @issue})) %>');

app/views/branches/new.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'branches/new') %>');
showModal('ajax-modal', '400px');
$('#ajax-modal').addClass('new-branch');

app/views/counter_repositories/_form.html.erb
<div class="box tabular">
  <%= labelled_form_for @repository do |f| %>
      <input name="project_id" type="hidden" value="<%= @project.identifier %>">

      <p><%= f.text_field :name %></p>

      <p><%= f.text_field :url %></p>
      </div>
      <%= submit_tag l(:button_submit) %>
  <% end %>

app/views/counter_repositories/edit.html.erb
<h2><%= @repository.name %></h2>
<%= render :partial => 'counter_repositories/form' %>

app/views/counter_repositories/index.html.erb
<div class="contextual">
  <%= link_to(l(:label_repository_new), new_counter_repository_path(@project), :class => 'icon icon-add') %>
</div>

<h2><%= l(:label_repository_plural) %></h2>
<% if @repositories.count > 0 %>
    <table class="list">
      <thead>
      <tr>
        <th><%= l(:field_repository_name) %></th>
        <th><%= l(:field_repository_url) %></th>
        <th></th>
      </tr>
      </thead>

      <% @repositories.each do |repo| %>
          <tr>
            <td><%= repo.name %></td>
            <td><%= repo.url %></td>
            <td>
              <%= link_to image_tag('edit.png'), edit_counter_repository_path(repo.id), :class => "edit" %>
              <%= link_to(image_tag('delete.png'), counter_repository_path(repo.id),
                          :method => 'delete', :class => "delete") %>

            </td>
          </tr>
      <% end %>

    </table>
<% else %>
    <p><%= l(:label_no_repositories) %></p>
<% end %>

app/views/counter_repositories/new.html.erb
<h2><%= l(:label_new_repository) %> - <%= @project.name %></h2>
<%= render :partial => 'counter_repositories/form' %>

app/views/monitoring/_fields.html.erb
<tr>
  <th class="status">Size:</th>
  <td class="status"><%= @issue.ticket_size %> lines</td>
  <th class="start-date">Inspection Preparation Time:</th>
  <td class="start-date"><%= Time.at(@issue.inspection_preparation_time).utc.strftime("%H:%M") %> hours</td>
</tr>
<tr>
  <th class="status">Inspection Time:</th>
  <td class="status"><%= Time.at(@issue.inspection_time).utc.strftime("%H:%M")  %> hours</td>
  <th class="start-date">Inspection Rework Time:</th>
  <td class="start-date"><%= Time.at(@issue.inspection_rework_time).utc.strftime("%H:%M") %> hours</td>
</tr>

app/views/monitoring/_list.erb
<%= form_tag({}) do -%>
    <%= hidden_field_tag 'back_url', url_for(params), :id => nil %>
    <div class="autoscroll">
      <table class="list issues">
        <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= link_to image_tag('toggle_check.png'), {},
                        :onclick => 'toggleIssuesSelection(this); return false;',
                        :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <% query.inline_columns.each do |column| %>
              <%= column_header(column) %>
          <% end %>
        </tr>
        </thead>
        <% previous_group = false %>
        <tbody>
        <% issue_list(issues) do |issue, level| -%>
            <% if @query.grouped? && (group = @query.group_by_column.value(issue)) != previous_group %>
                <% reset_cycle %>
                <tr class="group open">
                  <td colspan="<%= query.inline_columns.size + 2 %>">
                    <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
                    <%= group.blank? ? l(:label_none) : column_content(@query.group_by_column, issue) %> <span class="count"><%= @issue_count_by_group[group] %></span>
                    <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                                         "toggleAllRowGroups(this)", :class => 'toggle-all') %>
                  </td>
                </tr>
                <% previous_group = group %>
            <% end %>
            <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
              <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", issue.id, false, :id => nil) %></td>
              <%= raw query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, issue)}</td>"}.join %>
            </tr>
            <% @query.block_columns.each do |column|
              if (text = column_content(column, issue)) && text.present? -%>
                    <tr class="<%= current_cycle %>">
                      <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>"><%= text %></td>
                    </tr>
                <% end -%>
            <% end -%>
        <% end -%>
        </tbody>
      </table>
    </div>
<% end -%>

app/views/monitoring/index.html.erb
<h2><%= l(:label_monitoring_reports) %></h2>



<%= form_tag({:controller => 'monitoring', :action => 'index', :project_id => @project},
             :method => :get, :id => 'query_form') do %>
    <div id="query_form_with_buttons" class="hide-when-print">
      <%= hidden_field_tag 'set_filter', '1' %>
      <div id="query_form_content">
        <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
          <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
          <div style="<%= @query.new_record? ? "" : "display: none;" %>">
            <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
          </div>
        </fieldset>
        <fieldset class="collapsible collapsed">
          <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
          <div style="display: none;">
            <table>
              <tr>
                <td><%= l(:field_column_names) %></td>
                <td><%= render_query_columns_selection(@query) %></td>
              </tr>
              <tr>
                <td><label for='group_by'><%= l(:field_group_by) %></label></td>
                <td><%= select_tag('group_by',
                                   options_for_select(
                                           [[]] + @query.groupable_columns.collect { |c| [c.caption, c.name.to_s] },
                                           @query.group_by)
                        ) %></td>
              </tr>
              <tr>
                <td><%= l(:button_show) %></td>
                <td><%= available_block_columns_tags(@query) %></td>
              </tr>
            </table>
          </div>
        </fieldset>
      </div>
      <p class="buttons">
        <%= link_to_function l(:button_apply), 'submit_query_form("query_form")', :class => 'icon icon-checked' %>
        <%= link_to l(:button_clear), {:set_filter => 1, :project_id => @project}, :class => 'icon icon-reload' %>
        <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
            <%= link_to_function l(:button_save),
                                 "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }'); submit_query_form('query_form')",
                                 :class => 'icon icon-save' %>
        <% end %>
      </p>
    </div>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
    <% if @issues.empty? %>
        <p class="nodata"><%= l(:label_no_data) %></p>
    <% else %>
        <%= render :partial => 'monitoring/list', :locals => {:issues => @issues, :query => @query} %>
        <p class="pagination"><%= pagination_links_full @issue_pages, @issue_count %></p>
    <% end %>

    <% other_formats_links do |f| %>
        <%= f.link_to 'Atom', :url => params.merge(:key => User.current.rss_key) %>
        <%= f.link_to 'CSV', :url => params, :onclick => "showModal('csv-export-options', '350px'); return false;" %>
        <%= f.link_to 'PDF', :url => params %>
    <% end %>

    <div id="csv-export-options" style="display:none;">
      <h3 class="title"><%= l(:label_export_options, :export_format => 'CSV') %></h3>
      <%= form_tag(params.merge({:format => 'csv',:page=>nil}), :method => :get, :id => 'csv-export-form') do %>
          <p>
            <label><%= radio_button_tag 'columns', '', true %> <%= l(:description_selected_columns) %></label><br />
            <label><%= radio_button_tag 'columns', 'all' %> <%= l(:description_all_columns) %></label>
          </p>
          <p>
            <label><%= check_box_tag 'description', '1', @query.has_column?(:description) %> <%= l(:field_description) %></label>
          </p>
          <% if @issue_count > Setting.issues_export_limit.to_i %>
              <p class="icon icon-warning">
                <%= l(:setting_issues_export_limit) %>: <%= Setting.issues_export_limit.to_i %>
              </p>
          <% end %>
          <p class="buttons">
            <%= submit_tag l(:button_export), :name => nil, :onclick => "hideModal(this);" %>
            <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
          </p>
      <% end %>
    </div>

<% end %>

app/views/projects/settings/_monitoring.html.erb
<%= labelled_form_for @project,
             :url => { :action => 'monitoring_settings', :id => @project },
             :html => {:id => 'monitoring-form',
                       :method => :post} do |f| %>

    <div class="box tabular">
      <p>        
        <%= f.text_field :inspection_preparation_average, :size => 30, :value => @project.inspection_preparation_average ? @project.inspection_preparation_average : Setting.plugin_monitoring['inspection_preparation_average']   %>
      </p>
      <p>        
        <%= f.text_field :inspection_average, :size => 30, :value => @project.inspection_average ? @project.inspection_average : Setting.plugin_monitoring['inspection_average'] %>
      </p>
      <p>        
        <%= f.text_field :rework_average, :size => 30, :value => @project.rework_average ? @project.rework_average : Setting.plugin_monitoring['rework_average'] %>
      </p>
      <p>        
        <%= f.text_field :productivity_average, :size => 30, :value => @project.productivity_average ? @project.productivity_average : Setting.plugin_monitoring['productivity_average'] %>
      </p>
      <hr/>
      <table>
        <thead>
          <th>&nbsp;</th>
          <% complexities = CustomField.where(:name => 'Complexity').first.possible_values %>
          <% complexities.each do |complexity| %>
            <th><%= complexity %></th>
          <% end %>
        </thead>
        <tbody>          
          <% @project.trackers.each do |t| %>            
            <tr>
              <td><strong><%= t.name %></strong></td>  
              <% complexities.each do |complexity| %>
                <td>
                  <% c = @project.correction_factors.where(:tracker_id => t.id, :complexity => complexity).first %>
                  <% value = c.value unless c.nil? %>
                  <input name="correction_factors[][value]" type="number" value="<%= value %>" step="0.01"/>
                  <input name="correction_factors[][tracker_id]" value="<%= t.id %>"type="hidden" step="0.01"/>
                  <input name="correction_factors[][complexity]" value="<%= complexity %>"type="hidden" step="0.01"/>
                </td>
            <% end %>
            </tr>
          <% end %>

        </tbody>
      </table>

      

    </div>

    <p><%= submit_tag l(:button_save) %></p>

<% end %>

app/views/settings/_monitoring_settings.html.erb
<table>
  <tbody>
  <tr>
    <th>Inspection Preparation Average</th>
    <td><input type="text" id="inspection_preparation_average"
               value="<%= settings['inspection_preparation_average'] %>"
               name="settings[inspection_preparation_average]"></td>
    <td>Lines Per Hour</td>
  </tr>
  <tr>
    <th>Inspection Average</th>
    <td><input type="text" id="inspection_average"
               value="<%= settings['inspection_average'] %>"
               name="settings[inspection_average]"></td>
    <td>Lines Per Hour</td>
  </tr>
  <tr>
    <th>Inspection Rework Average</th>
    <td><input type="text" id="rework_average"
               value="<%= settings['rework_average'] %>"
               name="settings[rework_average]"></td>
    <td>Lines Per Hour</td>
  </tr>
  <tr>
    <th>Productivity Average</th>
    <td><input type="text" id="productivity_average"
               value="<%= settings['productivity_average'] %>"
               name="settings[productivity_average]"></td>
    <td>Lines Per Hour</td>
  </tr>  
  </tbody>
</table>